{
 "title": "LogiStock - Supervision",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latence moyenne (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(logistock_latence_secondes_sum[5m]) / rate(logistock_latence_secondes_count[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes HTTP (total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logistock_requetes_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disque (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}